In [1]:
import numpy as np

# Parameters
lam = 0.2
lower_bound = 2
upper_bound = 10

# CDF function for exponential distribution
def exponential_cdf(x, lam):
    return 1 - np.exp(-lam * x)

# Calculate P(2 < x < 10)
probability = exponential_cdf(upper_bound, lam) - exponential_cdf(lower_bound, lam)
print("P(2 < x < 10) =", probability)


P(2 < x < 10) = 0.5349847627990266


In [2]:
import numpy as np

# Parameters
p = 0.22
n = 21

# Calculate variance
variance = n * p * (1 - p)
print("Variance of X:", variance)


Variance of X: 3.6036


In [3]:
# Calculate the area of the rectangle
rectangle_area = (8 - 6) * (1 / 9)

# Calculate the area of the shaded region
shaded_area = 2 * (1 / 9)

# Calculate the probability
probability = shaded_area / rectangle_area

print("Probability that x falls in the shaded area:", probability)


Probability that x falls in the shaded area: 1.0


In [4]:
import numpy as np

# Values of the random variable X
x_values = [0, 1]

# Probabilities corresponding to each value
probabilities = [0.5, 0.5]

# Calculate the mean of X
mean = np.sum([x * p for x, p in zip(x_values, probabilities)])

# Calculate the standard deviation
std_dev = np.sqrt(np.sum([(x - mean) ** 2 * p for x, p in zip(x_values, probabilities)]))

print("Standard deviation of X:", std_dev)


Standard deviation of X: 0.5


In [5]:
import numpy as np

# Parameter
lam = 0.2

# Calculate the median
median = np.log(2) / lam

print("Median of the exponential distribution:", median)


Median of the exponential distribution: 3.465735902799726


In [6]:
# Values of the random variable X
x_values = [0, 1]

# Probabilities corresponding to each value
probabilities = [0.5, 0.5]

# Calculate the expected value of X
expected_value = sum(x * p for x, p in zip(x_values, probabilities))

print("Expected value of X:", expected_value)


Expected value of X: 0.5


In [7]:
from scipy.stats import uniform

# Define the range of the continuous distribution
lower_bound = 0
upper_bound = 10

# Calculate the PDF at x = 7
pdf_at_7 = uniform.pdf(7, loc=lower_bound, scale=upper_bound - lower_bound)

print("Probability density at x = 7:", pdf_at_7)


Probability density at x = 7: 0.1


In [8]:
from scipy.integrate import quad

# Define the continuous uniform PDF function over the interval [0, 10]
def pdf_function(x):
    if 0 <= x <= 10:
        return 1 / (10 - 0)
    else:
        return 0

# Calculate the total area under the PDF curve
total_area, _ = quad(pdf_function, 0, 10)

print("Total area under the PDF curve:", total_area)


Total area under the PDF curve: 1.0000000000000002


In [9]:
import numpy as np

# Parameters
lam = 0.2
x = 6

# CDF function for exponential distribution
def exponential_cdf(x, lam):
    return 1 - np.exp(-lam * x)

# Calculate P(x > 6)
probability = 1 - exponential_cdf(x, lam)
print("P(x > 6) =", probability)


P(x > 6) = 0.30119421191220197


In [10]:
# Parameters
p = 0.22
n = 21

# Calculate the expected value
expected_value = n * p

print("Expected value of X:", expected_value)


Expected value of X: 4.62


In [11]:
import numpy as np

# Parameters
lam = 0.2
p = 0.7

# Inverse CDF function for exponential distribution
def exponential_inv_cdf(p, lam):
    return -np.log(1 - p) / lam

# Calculate the 70th percentile
percentile_70 = exponential_inv_cdf(p, lam)
print("70th percentile of the exponential distribution:", percentile_70)


70th percentile of the exponential distribution: 6.0198640216296795


In [12]:
Question 19
Not yet answered
Marked out of 1.00
Flag question
Question text
A call center technical specialist spends varying amount of time in each call to resolve the concern. The time spent in each call is modeled using the following distribution: X~ Exp (0.2).

What is the mean?


Question 19Answer

a.
1


b.
5


c.
2

SyntaxError: invalid decimal literal (9989378.py, line 11)

In [14]:
# Parameter
lam = 0.2

# Calculate the mean
mean = 1 / lam

print("Mean of the exponential distribution:", mean)


Mean of the exponential distribution: 5.0


In [15]:
# Parameter
lam = 0.2

# Calculate the standard deviation
std_dev = 1 / lam

print("Standard deviation of the exponential distribution:", std_dev)


Standard deviation of the exponential distribution: 5.0


In [16]:
# Width of the shaded region
width_shaded = 8 - 6

# Height of the shaded region (line on top)
height_shaded = 1 / 9

# Calculate the area of the shaded region
area_shaded = width_shaded * height_shaded

# Calculate the total area (area of the rectangle)
area_total = width_shaded * height_shaded

# Calculate the probability
probability = area_shaded / area_total

print("Probability that x falls in the shaded area:", probability)


Probability that x falls in the shaded area: 1.0


In [17]:
from scipy.integrate import quad

# Define the continuous probability density function (PDF)
def pdf_function(x):
    # For this example, let's assume a uniform distribution over the interval [0, 15]
    if 0 <= x <= 15:
        return 1 / 15  # PDF is constant over the interval [0, 15]
    else:
        return 0  # PDF is zero outside the interval [0, 15]

# Calculate the probability of x > 15 by integrating the PDF over the range x > 15
probability, _ = quad(pdf_function, 15, float('inf'))

print("Probability that x > 15:", probability)


Probability that x > 15: 0.0


In [18]:
# Width of the shaded region
width_shaded = 8 - 6

# Height of the shaded region
height_shaded = 1 / 9

# Calculate the area of the shaded region
area_shaded = width_shaded * height_shaded

# Calculate the total area (area of the rectangle)
area_total = width_shaded * height_shaded

# Calculate the probability
probability = area_shaded / area_total

print("Probability that x falls in the shaded area:", probability)


Probability that x falls in the shaded area: 1.0


In [19]:
# Width of the shaded region
width_shaded = 5 - 0

# Height of the shaded region
height_shaded = 1 / 8

# Calculate the area of the shaded region
area_shaded = width_shaded * height_shaded

# Calculate the total area (area of the rectangle)
area_total = width_shaded * height_shaded

# Calculate the probability
probability = area_shaded / area_total

print("Probability that x falls in the shaded area:", probability)


Probability that x falls in the shaded area: 1.0


In [20]:
# Width of the shaded region
width_shaded = 8 - 6

# Height of the shaded region
height_shaded = 1 / 9

# Calculate the area of the shaded region
area_shaded = width_shaded * height_shaded

print("Probability that x falls between 6 and 8:", area_shaded)


Probability that x falls between 6 and 8: 0.2222222222222222


In [21]:
# Width of the shaded region
width_shaded = 5 - 0

# Height of the shaded region
height_shaded = 1 / 8

# Calculate the area of the shaded region
area_shaded = width_shaded * height_shaded

print("Probability that x falls between 0 and 5:", area_shaded)


Probability that x falls between 0 and 5: 0.625


In [22]:
from sympy import symbols, solve

# Define the variable and function
x = symbols('x')
f = x**2 + 3

# Evaluate f(x) at the endpoints
f_minus_1 = f.subs(x, -1)
f_4 = f.subs(x, 4)

# Find the critical point
critical_points = solve(f.diff(x), x)

# Evaluate f(x) at the critical point(s)
f_critical = [f.subs(x, cp) for cp in critical_points]

# Determine the maximum value
absolute_maximum = max(f_minus_1, f_4, *f_critical)

print("Absolute maximum value:", absolute_maximum)


Absolute maximum value: 19


In [23]:
from sympy import symbols, diff

# Define the variable and the function
x = symbols('x')
y = (x - 1/x)**4

# Compute the derivative of y with respect to x
dy_dx = diff(y, x)

# Evaluate the derivative at x = 1
gradient_at_1 = dy_dx.subs(x, 1)

print("Gradient of the tangent at x = 1:", gradient_at_1)


Gradient of the tangent at x = 1: 0


In [24]:
from sympy import symbols, sin, cos, pi

# Define the variable and the function
x = symbols('x')
y = sin(x)**2

# Compute the derivative of y with respect to x
dy_dx = y.diff(x)

# Evaluate the derivative at x = pi/3
gradient_at_pi_over_3 = dy_dx.subs(x, pi/3)

print("Gradient of the tangent at x = pi/3:", gradient_at_pi_over_3)


Gradient of the tangent at x = pi/3: sqrt(3)/2


In [25]:
from sympy import symbols, diff

# Define the variable and the function
x = symbols('x')
y = (2 - 3*x)**5

# Compute the derivative of y with respect to x
dy_dx = diff(y, x)

# Evaluate the derivative at x = 1
gradient_at_1 = dy_dx.subs(x, 1)

print("Gradient of the tangent at x = 1:", gradient_at_1)


Gradient of the tangent at x = 1: -15


In [26]:
from sympy import symbols, cot, diff

# Define the variable and function
x = symbols('x')
y = cot(5*x)

# Compute the derivative
derivative = diff(y, x)

# Print the result
print("The derivative of y = cot^(-1)(5x) with respect to x is:", derivative)


The derivative of y = cot^(-1)(5x) with respect to x is: -5*cot(5*x)**2 - 5


In [27]:
from sympy import symbols, cot, diff, atan

# Define the variable and the function
x = symbols('x')
y = atan(5*x)

# Find the derivative
derivative_y = diff(y, x)

print("The derivative of y =", derivative_y)


The derivative of y = 5/(25*x**2 + 1)


In [28]:
from sympy import symbols, asin, diff, sqrt

# Define the variable and the function
x = symbols('x')
g_inv = asin(x)

# Find the derivative
derivative_g_inv = diff(g_inv, x)

# Simplify the derivative
derivative_g_inv_simplified = derivative_g_inv.simplify()

print("The derivative of g^-1(x) =", derivative_g_inv_simplified)


The derivative of g^-1(x) = 1/sqrt(1 - x**2)


In [29]:
from sympy import symbols, acos, diff, sqrt

# Define the variable and the function
x = symbols('x')
y = acos(3*x)

# Find the derivative
derivative_y = diff(y, x)

print("The derivative of y =", derivative_y)


The derivative of y = -3/sqrt(1 - 9*x**2)


In [30]:
from sympy import symbols, cot, diff

# Define the variable and the function
x = symbols('x')
y = cot(5*x)**-1

# Find the derivative
derivative_y = diff(y, x)

print("The derivative of y with respect to x is:", derivative_y)


The derivative of y with respect to x is: (5*cot(5*x)**2 + 5)/cot(5*x)**2


In [2]:
import sympy as sp

# Define the symbols
r = sp.symbols('r')

# Define the characteristic equation
eq = 2 * r**2 - 5 * r + 3

# Solve the characteristic equation for roots
roots = sp.solve(eq, r)

# Define initial conditions
a0 = 1
a1 = 5

# Define the recurrence relation
n = sp.symbols('n')
an = sp.Function('a')(n)

# Define the general solution
general_solution = sum(c * r**n for c, r in zip(sp.symbols('c1:4'), roots))

# Substitute initial conditions to find constants c1, c2, and c3
constants = sp.solve((general_solution.subs(n, 0) - a0, general_solution.subs(n, 1) - a1))

# Substitute the constants into the general solution
solution = general_solution.subs(constants)

# Print the solution
print("The solution to the recurrence relation is:")
print(solution)


The solution to the recurrence relation is:
8*(3/2)**n - 7


In [3]:
import numpy as np

# Define the matrix R
R = np.array([[1, 0, 1],
              [1, 1, 1],
              [1, 0, 0]])

# Calculate R^2 using matrix multiplication
R_squared = np.dot(R, R)

# Print the result
print("R^2 =")
print(R_squared)


R^2 =
[[2 0 1]
 [3 1 2]
 [1 0 1]]


In [4]:
import sympy as sp

# Define symbolic variables
P, Q = sp.symbols('P Q')

# Define the logical expressions
expression = sp.And(Q >> P, sp.Not(P >> Q))

# Simplify the expression
simplified_expression = sp.simplify(expression)

# Print the simplified expression
print("Simplified expression:", simplified_expression)


Simplified expression: P & ~Q


In [5]:
def solve_recurrence_relation(n):
    a = [0] * (n + 1)
    a[0] = 1  # Initial condition a0 = 1

    for i in range(1, n + 1):
        a[i] = (6 * a[i - 1] - 4) / 2

    return a[n]

# Test the function for some values of n
print("a_1 =", solve_recurrence_relation(1))
print("a_2 =", solve_recurrence_relation(2))
print("a_3 =", solve_recurrence_relation(3))


a_1 = 1.0
a_2 = 1.0
a_3 = 1.0


In [6]:
# Calculate the value of k
k = (4374 / 2) ** (1/7)

# Print the value of k
print("The value of k is:", k)


The value of k is: 3.0


In [7]:
def F(x):
    return x + 2 >= 6

# Test each option
options = {
    "a": F(4),
    "b": F(7),
    "c": F(6),
    "d": F(2)
}

# Print the results
for option, value in options.items():
    print(f"Option {option}: {value}")


Option a: True
Option b: True
Option c: True
Option d: False


In [8]:
def check_divisibility(n, divisor):
    return (13 ** n - 1) % divisor == 0

# Test divisibility for different values of n
for n in range(1, 11):
    print(f"For n = {n}:")
    print("Divisible by 11:", check_divisibility(n, 11))
    print("Divisible by 12:", check_divisibility(n, 12))
    print("Divisible by 13:", check_divisibility(n, 13))
    print("Prime number:", all(check_divisibility(n, i) for i in range(2, n)))
    print()


For n = 1:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: True

For n = 2:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: True

For n = 3:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: True

For n = 4:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: True

For n = 5:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: True

For n = 6:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: False

For n = 7:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: False

For n = 8:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: True

For n = 9:
Divisible by 11: False
Divisible by 12: True
Divisible by 13: False
Prime number: False

For n = 10:
Divisible by 11: True
Divisible by 12: True
Divisible by 13: False
Prime number: False



In [9]:
import numpy as np

# Define the set A
A = [5, 10, 15, 20, 30]

# Initialize the adjacency matrix with zeros
adjacency_matrix = np.zeros((len(A), len(A)), dtype=int)

# Populate the adjacency matrix based on the relation
for i in range(len(A)):
    for j in range(len(A)):
        if A[j] % A[i] == 0:  # Check if A[i] divides A[j]
            adjacency_matrix[i][j] = 1

# Print the adjacency matrix
print("The adjacency matrix is:")
print(adjacency_matrix)


The adjacency matrix is:
[[1 1 1 1 1]
 [0 1 0 1 1]
 [0 0 1 0 1]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [10]:
import networkx as nx
import matplotlib.pyplot as plt

# Create a directed graph
G = nx.DiGraph()

# Add nodes
nodes = ['a', 'b', 'c', 'd']
G.add_nodes_from(nodes)

# Add edges
edges = [('a', 'a'), ('a', 'b'), ('a', 'c'), ('a', 'd'),
         ('b', 'b'), ('b', 'd'),
         ('c', 'c'),
         ('d', 'd')]
G.add_edges_from(edges)

# Draw the graph
pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=2000, node_color='skyblue', font_size=20, font_weight='bold', arrowsize=20)

# Show the Hasse diagram
plt.title('Hasse Diagram of the Partial Order Set')
plt.show()


TypeError: '_AxesStack' object is not callable

<Figure size 640x480 with 0 Axes>