In [1]:
import numpy as np
import sympy as sp

In [7]:
arx = np.random.rand(7)
ary = np.random.rand(7,7)

In [8]:
arx

array([0.10415854, 0.24764035, 0.72045454, 0.57106755, 0.04892668,
       0.05736506, 0.80075788])

In [9]:
ary

array([[0.71047628, 0.74295145, 0.89397434, 0.39885177, 0.43407192,
        0.929113  , 0.1660118 ],
       [0.57786142, 0.68868814, 0.63071716, 0.34991557, 0.97426565,
        0.78257966, 0.21163812],
       [0.48759498, 0.750937  , 0.74272725, 0.02820765, 0.42535529,
        0.03910078, 0.62517649],
       [0.45114868, 0.97189135, 0.90338575, 0.89756835, 0.26388174,
        0.16340553, 0.99961852],
       [0.48584363, 0.47313408, 0.8581797 , 0.12713007, 0.4727533 ,
        0.25684144, 0.36124087],
       [0.69727542, 0.18777985, 0.71178209, 0.83402419, 0.33077301,
        0.63169174, 0.31854481],
       [0.15653652, 0.79311042, 0.73631088, 0.08149274, 0.87278846,
        0.47610153, 0.22167221]])

In [13]:
multiplication = np.dot(arx,ary)
multiplication

array([1.01514818, 2.0129736 , 1.97272764, 0.78041138, 1.48462053,
       0.84210477, 1.30441606])

In [14]:
x,y = sp.symbols('x y')

In [17]:
eq1 = sp.Eq(2*x+y,5)
eq2 = sp.Eq(x-y,5-1)

eq1
solution = sp.solve((eq1,eq2),(x,y))
solution

{x: 3, y: -1}

In [1]:
topics = [
    ("Introduction to Linear Algebra", "Basic concepts of vectors, matrices, and vector spaces. Introduction to linear transformations and their properties."),
    ("Systems of Linear Equations", "Solving systems of linear equations using matrix methods such as Gaussian elimination and matrix inversion."),
    ("Matrix Operations", "Understanding basic matrix operations including addition, subtraction, scalar multiplication, and matrix multiplication."),
    ("Determinants", "Introduction to determinants and their properties. Understanding the geometric interpretation of determinants."),
    ("Vector Spaces", "Exploring the properties of vector spaces, subspaces, and linear independence. Introduction to basis and dimension."),
    ("Eigenvalues and Eigenvectors", "Understanding eigenvalues and eigenvectors of matrices. Applications in stability analysis, principal component analysis (PCA), and diagonalization."),
    ("Orthogonality", "Introduction to orthogonal vectors, orthogonal projections, and orthogonal matrices. Applications in least squares regression and QR decomposition."),
    ("Singular Value Decomposition (SVD)", "Understanding the singular value decomposition and its applications in dimensionality reduction, data compression, and least squares approximation."),
    ("Linear Transformations", "Further exploration of linear transformations, including rotation, reflection, and scaling. Understanding the matrix representation of transformations."),
    ("Inner Product Spaces", "Introduction to inner product spaces, norms, and orthogonality. Applications in vector projections and orthogonality."),
    ("Applications in Machine Learning", "Exploring various applications of linear algebra in machine learning, including linear regression, PCA, support vector machines (SVM), and neural networks.")
]

In [2]:

import os
import json

# Loop through the list of topics and create notebooks
for index, (topic, description) in enumerate(topics, start=1):
    # Construct the notebook filename
    notebook_filename = f"./{index:02d}_{topic.replace(' ', '_')}.ipynb"
    
    # Write description to the top cell of the notebook
    notebook_content = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# {topic}",
                    "",
                    description
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.11"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }
    
    # Write notebook content to file
    with open(notebook_filename, "w") as file:
        json.dump(notebook_content, file)

print("Notebooks created successfully!")


Notebooks created successfully!
