In [3]:
import torch
from torch import nn
import numpy as np

In [9]:
haha = torch.Tensor(4,4)

In [11]:
haha.numpy()

array([[1.4666157e-11, 1.7263997e-42, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00]],
      dtype=float32)

In [22]:
lmao = torch.ones(2,2).numpy()
lol = torch.ones(2,2).numpy()


In [24]:
print(lmao.cross(lol))

AttributeError: 'numpy.ndarray' object has no attribute 'cross'

In [26]:
emb=  nn.Embedding(4,4)

In [27]:
emb(lol)

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not numpy.ndarray

In [154]:
train = [
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
]
train=np.array(train)
train = torch.tensor(train,dtype=torch.long)

label =[
    [6],[7],[8],[9],
    [6],[7],[8],[9],
    [6],[7],[8],[9],
    [6],[7],[8],[9],
    [6],[7],[8],[9],
    [6],[7],[8],[9],
    [6],[7],[8],[9],
    [6],[7],[8],[9],

]

label = torch.tensor(label,dtype=torch.long)


In [155]:
import torchvision
import torchvision.transforms as trans

class Dot(torch.utils.data.Dataset):
    def __init__(self):
        super(torch.utils.data.Dataset,self).__init__()
        self.data = train
        self.labels = label
        # self.transforms = torch.Tensor


    def __len__(self):
        return len(self.data)
    
    def __getitem__(self,index):
        x = self.data[index]/10
        y = self.labels[index]/10
        return x,y
        


In [156]:
data = Dot()

len(data)

data[0]


(tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000]), tensor([0.6000]))

In [157]:
class TorchNet(nn.Module):
    def __init__(self, ) -> None:
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(5,8),
            nn.ReLU(),
            nn.Linear(8,4),
            nn.Linear(4,1),

            # nn.Softmax()
        )

    def forward(self,x):
        return self.model(x)

In [158]:
net = TorchNet()
optim = torch.optim.Adam(net.parameters(),lr=0.001)
loss_fn = nn.CrossEntropyLoss()


trainset = torch.utils.data.DataLoader(data,shuffle=True)


In [159]:
for epoch in range(200):
    for i,(dt,label) in enumerate(trainset):
        optim.zero_grad()
        print('label',label)

        # print(len(dt))

        pred = net(dt)
        print('pred',pred)
        loss = loss_fn(pred,label)
        # print('loss',loss)
        loss.backward()
        print('losssss->',loss.item())
        optim.step()


    


label tensor([[0.6000]])
pred tensor([[-0.0154]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.8000]])
pred tensor([[-0.0171]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.7000]])
pred tensor([[-0.0163]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.8000]])
pred tensor([[-0.0171]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.8000]])
pred tensor([[-0.0171]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.8000]])
pred tensor([[-0.0171]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.9000]])
pred tensor([[-0.0180]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.8000]])
pred tensor([[-0.0171]], grad_fn=<AddmmBackward0>)


label tensor([[0.7000]])
pred tensor([[-0.0163]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.8000]])
pred tensor([[-0.0171]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.6000]])
pred tensor([[-0.0154]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.9000]])
pred tensor([[-0.0180]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.9000]])
pred tensor([[-0.0180]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.6000]])
pred tensor([[-0.0154]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.8000]])
pred tensor([[-0.0171]], grad_fn=<AddmmBackward0>)
loss tensor(-0., grad_fn=<DivBackward1>)
losssss-> -0.0
label tensor([[0.7000]])
pred tensor([[-0.0163]], grad_fn=<AddmmBackward0>)


In [163]:
train.shape

train.view(-1).shape

torch.Size([160])

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]])