In [2]:
import numpy as np

In [3]:
# Create a 1D array from a Python list
arr1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array (matrix) from a list of lists
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create an array filled with zeros
zeros_arr = np.zeros((3, 4))  # Creates a 3x4 array filled with zeros

# Create an array filled with ones
ones_arr = np.ones((2, 3))  # Creates a 2x3 array filled with ones

# Create an array with a range of values
range_arr = np.arange(0, 10, 2)  # Creates an array from 0 to 10 (exclusive) with step 2

# Create an array with evenly spaced values
linspace_arr = np.linspace(0, 5, 10)  # Creates 10 evenly spaced values from 0 to 5

In [8]:
one = np.random.rand(4)

In [9]:
one.shape

(4,)

In [10]:
two = np.random.rand(5,2)

In [11]:
two

array([[0.6013653 , 0.89801867],
       [0.94198053, 0.95190621],
       [0.13185677, 0.10994867],
       [0.96570963, 0.0638187 ],
       [0.83430771, 0.78869438]])

In [12]:
two.shape

(5, 2)

In [13]:
multi= np.random.rand(4,5,2,8)

In [14]:
multi

array([[[[7.94403778e-01, 4.01850870e-01, 9.21953522e-01,
          6.96461526e-01, 6.96493183e-02, 3.44827342e-01,
          7.31086142e-01, 9.86320363e-01],
         [4.62522143e-01, 8.88952795e-01, 2.66179218e-01,
          6.83562839e-01, 1.85116501e-01, 1.35014838e-01,
          6.49615772e-01, 7.43263757e-01]],

        [[7.43673049e-01, 4.28423571e-01, 5.13638678e-01,
          3.95093309e-01, 2.38525685e-01, 9.41810043e-01,
          2.62182127e-01, 2.55017963e-02],
         [7.72617365e-01, 8.83143690e-01, 6.33647072e-01,
          4.93310556e-01, 5.07935793e-01, 3.30294934e-02,
          1.66153151e-01, 2.46269783e-01]],

        [[4.33669608e-01, 7.68730250e-01, 2.06251612e-01,
          8.44179486e-01, 6.20672656e-01, 9.43494970e-01,
          5.97975929e-01, 5.22353835e-01],
         [9.39510201e-01, 8.00963998e-02, 5.89657552e-01,
          2.13455339e-02, 7.70442586e-01, 8.90438302e-01,
          8.01707112e-01, 1.05766411e-01]],

        [[8.38753660e-01, 5.86375667e-01

In [16]:
using_one = np.ones((4,5))

In [17]:
using_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
arr_one = np.random.rand(2,4)

In [19]:
array_two = np.random.rand(2,4)

In [20]:
array_two

array([[0.34784375, 0.87527968, 0.17077569, 0.34050045],
       [0.32300975, 0.99662945, 0.37040479, 0.10369778]])

In [21]:
arr_one

array([[0.52285679, 0.37763525, 0.29448756, 0.18308838],
       [0.75256205, 0.86635155, 0.25361244, 0.60696296]])

In [23]:
result = arr_one + array_two

In [26]:
multiply = arr_one * array_two

In [27]:
arr_one.shape

(2, 4)

In [28]:
multiply.shape

(2, 4)

In [33]:
m_1 = np.random.rand(4,2)

In [37]:
m2 = np.random.rand(2,4)

In [38]:
s = np.dot(m_1 , m2)

In [39]:
s

array([[0.90016262, 1.08287181, 0.90086985, 0.56578066],
       [0.69410146, 0.78901427, 0.67739728, 0.39779291],
       [0.32069406, 0.49802918, 0.363062  , 0.2954982 ],
       [1.172637  , 1.63565201, 1.25798362, 0.92533435]])

In [40]:
s.shape

(4, 4)